config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root to: 'recipes#index'
  resource :profile, :only => :show, :as => :current_profile
  resource :profile, only: [ :edit, :destroy, :update ]


  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :recipes, only: [ :index, :show, :new, :create ] do
    resources :reviews, only: [ :new, :create]
    collection do
      get 'search'
    end
  end

  resources :doses, only: [ :new, :create, :destroy, :edit, :update ]

  resources :ingredients

  resources :reviews, only: [ :destroy ]


  resources :favorites, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  mount_uploader :picture, PhotoUploader

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @profile = current_user.profile
    @favorites = current_user.favorites
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    @profile.update(profile_params)
    # no need for app/views/restaurants/update.html.erb
    redirect_to profile_path(@profile)
  end

  private

  def get_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :age, :picture, :user_id, :user_name, :quote)
  end
end

app/views/profiles/edit.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div class="flexi2">

      <fieldset>

        <%= simple_form_for(@profile) do |f| %>


        <div class='kickass_field'>
          <span class= "adapt"> First name</span>
          <%= f.input :first_name , label:false%>
        </div>

        <div class='kickass_field'>
            <span class= "adapt">Last name</span>
          <%= f.input :last_name ,label:false%>
        </div>

    <div class='kickass_field'>
       <span class= "adapt">Username</span>
        <%= f.input :user_name ,label:false%>
      </div>

      <div class='kickass_field'>
         <span class= "adapt">How old are you ?</span>
           <%= f.input :age,label:false %>
        </div><b>

      <div class='kickass_field'>
          <span class= "adapt">Favorite ingredient?</span>
        <%= f.input :quote, label:false %>
        </div>
        <div class="row">
        <div class="col-xs-12 col-sm-9 col-sm-offset-1">

       <%= f.submit "Update your profile", class: "button"%>
      <%= f.input :picture %>
      <%= f.input :picture_cache, as: :hidden, class: "form-control" %>

      </div>
    </div>

        <% end %>
      </fieldset>
      </div>
    </div>
  </div>
</div>


<!--

<fieldset>
<div class='kickass_field'>
<input maxlength='30' required='required'>
<lable>
Username
<span>Your chosen username</span>
</lable>
</div>
<div class='kickass_field'>
<input maxlength='30' required='required' type='email'>
<lable>
Email address
<span>Your current email address</span>
</lable>
</div>
<div class='kickass_field'>
<input maxlength='30' pattern='.{6,}' required='required' type='password'>
<lable>
Password
<span>Minimum of 6 characters</span>
</lable>
</div>
<button>Sign up</button>
</fieldset>
-->

app/views/profiles/show.html.erb
<div class="containerr">
  <div class="row">
    <div class="col-xs-12 col-lg-3 stick">
        <div class="kard hoverkard">
          <div class="kardheader">
            <% avatar_url = @profile.picture.url || "http://placehold.it/150x150" %>
            <%= image_tag avatar_url, class: "avatare" %>
          </div>

          <div class="infoe">
            <%if @profile.first_name%>
            <div class="title"> Bienvenue, <%="#{@profile.first_name}"%>  !</div>
            <%end%>
           <div class="desc"> email : <%=current_user.email %></div>

            <%if @profile.age%>
            <div class="desc"><%= "age : #{@profile.age} y.o"%></div>
            <%end%>
            <%if @profile.quote%>
            <div class="desc"> favorite ingredient : the <%=@profile.quote%></div>
            <%end%>
            <br>
            <b><%= link_to "customize your profile !", edit_profile_path(@profile), class: "btn-danger btn-goback"%></b>
          </div>


    </div>
</div>
<div class="col-xs-12 col-lg-9">
  <div class="kard favorite-section">
    <div class='favorite-hero'></div>
    <h1 class='favorite_head'> Your favorites recipes</h1>
    <div class='favorites'>
      <% if current_user and @favorites.length > 0 %>
      <% i = 1 %>
      <% @favorites.each do |favorite| %>
      <% recipe = Recipe.find(favorite.recipe_id) %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card-container">
          <%= link_to recipe_path(recipe) do %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= if recipe.picture.url == nil
            image_path('https://placeholdit.co//i/500x500?')
          else
            cl_image_path recipe.picture.url
          end
          %>')">
        </div>
        <%end%>

        <div class="link-box-profile">
          <%= link_to recipe_path(recipe) do %>
          <%=recipe.name.capitalize%>
          <% if recipe.reviews.size != 0 %>
          <% arr = [] %>
          <% recipe.reviews.each do |review| %>
          <% arr << review.rating %>
          <% end %>
          <% average = arr.inject{ |sum, el| sum + el }.to_f / arr.size %>
          <p> rating : <%= average.round(1) if average %> / 5</p>
          <% else %>
          <p> waiting for a rating !</p>
          <%end%>
          <%end%>
        </div>

      </div>
    </div>
    <% end %>
    <% else %>
    <h4><b>You don't have any favorite recipes?  <%= link_to 'Go Back', root_path, class: 'btn-danger btn-goback' %> and pick some as shown below !</b> </h4>

        <div class="card-containerbigger">
    <div class="cardbigger" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path("GIFF_h3ubwd.gif")%>')">
    </div>
</div>
    <% end %>
  </div>
</div>
</div>
</div>
</div>
</div>
</div>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>