config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root to: 'recipes#index'
  resource :profile, :only => :show, :as => :current_profile
  resource :profile, only: [ :edit, :destroy, :update ]


  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :recipes, only: [ :index, :show, :new, :create ] do
    resources :reviews, only: [ :new, :create]
    collection do
      get 'search'
    end
  end

  resources :doses, only: [ :new, :create, :destroy, :edit, :update ]

  resources :ingredients

  resources :reviews, only: [ :destroy ]


  resources :favorites, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
#  include AlgoliaSearch

  has_many :ingredients, through: :doses
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, uniqueness: true
  validates :name, presence: true
  mount_uploader :picture, PhotoUploader

#   algoliasearch per_environment: true do
#    attribute :name
#    attribute :picture
#    attribute :ingredients
#    searchableAttributes ['ingredients']
#  end

  def inline_ingredients
    ingredients.to_a.map(&:name).join(' ')
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
    @ingredients = Ingredient.all
    # if params[:search]
    #   if params[:search] == ""
    #     @recipes = Recipe.all
    #     respond_to do |format|
    #       format.html { redirect_to recipes_path}
    #       format.js
    #     end
    #   else
    #     @ingredient = params[:search]
    #     @recipes = params[:search]
    #     respond_to do |format|
    #     format.html { redirect_to recipes_path }
    #     format.js
    #     end
    #   end
    # else
    #   @recipes = Recipe.all
    # end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @review=Review.new
    @dose = Dose.new
    @ingredients = Ingredient.all
  end


end

app/helpers/recipes_helper.rb
module RecipesHelper

   def link_to_toggle_recipe_favorite(recipe)
    url = recipe_favorite_path(recipe)

    if recipe.favorited?
      link_to_with_icon('icon-star', 'Favorite', url, {
        method: 'DELETE',
        remote: true,
        class: 'favorite btn btn-primary',
      })
    else
      link_to_with_icon('icon-star', 'Favorite', url, {
        method: 'PUT',
        remote: true,
        class: 'favorite btn',
      })
    end
  end

  def link_to_with_icon(icon_css, title, url, options = {})
    icon = content_tag(:i, nil, class: icon_css)
    title_with_icon = icon << ' '.html_safe << h(title)
    link_to(title_with_icon, url, options)
  end
end

app/views/recipes/_reviews.html.erb
<div class="col-xs-8 col-xs-offset-2 col-lg-6 col-lg-offset-3" >

  <h3 class="grey">
    <b>  <% arr = [] %>
      <%if @recipe.reviews.size != 0 %>
      <% @recipe.reviews.each do |review| %>
      <% arr << review.rating %>
      <% end %>
      <% average = arr.inject{ |sum, el| sum + el }.to_f / arr.size %>
      <%end%>

      <%if average %>

      Average rating on this recipe :

      <% average.round(0).times do  %>
      <i class="fa fa-star"></i>
      <%end%>

      <% (5-average.round(0)).times do %>
      <i class="fa fa-star-o"></i>
      <%end%>
    <%else%>

  Be the first to add a review !

    <%end%>

    </br>
  </br>
</br>

</b>
</h3>
<br>
</div>



<div class="col-xs-8 col-xs-offset-2 col-lg-6 col-lg-offset-3 ">

  <%= simple_form_for [@recipe, @review] do |f| %>

  <div class="input-group", id="seereview">
    <span class="input-group-addon addon2"><i class="fa fa-pencil-square-o"></i></span>
    <%= f.input :content, placeholder: 'write your review',label:false, class: "form-control"  %>


  </div>
</br>
<div class="input-group">
  <span class="input-group-addon addon2"><i class="fa fa-star-half-o "></i></span>

  <%= f.input :rating, collection: 1..5,placeholder: 'rate this recipe', label:false,class: "form-control select"  %>
  <span class="input-group-addon addon2"><i class=""></i></span>

</div>
</br>

<div class="row">

  <div class="col-xs-8 col-xs-offset-2 col-lg-4 col-lg-offset-4">
    <%= f.submit "add a review", class: "btn btn-lg btn-primary btn-block btn-special ecriture colorblue" %>
  </div>
</div>


<% end %>
<br>
</div>



<div class="row">
  <div class="col-xs-8 col-xs-offset-2 col-lg-8 col-lg-offset-2 ">
    <div class ="row">
      <br>


      <% @recipe.reviews.reverse.each do |review| %>
      <% if review.picture.url == nil%>

      <ul class="message-box" id="content">
        <div class ="col-xs-3 col-lg-2">
          <div class ="user-box">
            <% avatar_url = review.user.profile.picture.url || "http://placehold.it/30x30" %>
            <%= image_tag avatar_url, class: "avatar" %>
            <p class="user-info"> <strong><%= review.user.profile.user_name %> </strong> <br> rate : <%= review.rating  %> / 5  </p>
          </div>
        </div>
        <div class ="col-xs-8 col-lg-7">
          <p class="patate"> <%=review.content %> </p>
        </div>
        <br>
      </ul>
      <p class="accepted">
        <strong>
        </strong>
        <br>
      </p>
      <%else%>
      <ul class="message-box" id="content">
        <div class ="col-xs-3 col-lg-4">
          <div class ="user-box">
            <% avatar_url = review.user.profile.picture.url || "http://placehold.it/30x30" %>
            <%= image_tag avatar_url, class: "avatar" %>
            <p class="user-info">
              <strong><%= review.user.profile.user_name %> </strong> <br> rate : <%= review.rating  %> / 5
            </p>
          </div>
        </div>

        <div class ="col-xs-5 col-lg-5">
          <p class="patate">
            <%=review.content %>
          </p>
        </div>
        <div class ="col-xs-3">
          <div class= "img">
            <%= cl_image_tag(review.picture.url, :width=>200, :height=>200, :gravity=>"south_east", :crop=>"crop", class: "thumbnail") %>
          </div>
        </div>
        <br>
      </ul>
      <p class="accepted">
        <strong><%= link_to "Delete", review_path(review), method: :delete, data: { confirm: "Are you sure?" }%>
        </strong>
        <br>
      </p>

      <% end %>
      <% end %>

    </div>
  </div>
</div>

</br>

</div>
</div>

app/views/recipes/_showimproved.html.erb
<div class="containerrr">
  <div class="row">
    <div class="col-xs-12 col-lg-3 stick">
      <div class="kardo hoverkard">


        <div class="infoe">

          <div class="cardoue" style="background-size: cover; background-repeat: no-repeat; background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= if @recipe.picture.url == nil
            image_path('https://placeholdit.co//i/500x500?', class: "picture-recipe")
          else
            cl_image_path @recipe.picture.url
          end
          %>')">
        </div>
        <div>
          <p class="share-recipe">
            <strong>SHARE THIS RECIPE </strong>
          </p>
          <%= social_share_button_tag(@recipe.name, 'data-twitter-title' => "Yum-yum, this recipe seems delicious !! #{@recipe.name}", 'data-facebook-title' => "Yum-yum, this recipe seems delicious !! #{@recipe.name}" )%>
        </div>
      </div>
    </div>




  </div>

  <div class="col-xs-12 col-lg-9">

    <div class="kardo favorite-section">

      <div class="row">

        <a class="pinned-item btn-special colorblue" href="#seereview"> See the reviews ! </a>


        <div class='row'>

          <div class="recipe-info-content">

            <div class="col-xs-12 col-lg-12">

              <div class="recipe-title ">
                <h2><%= @recipe.name.capitalize %></h2>
                          </br>
                           </br>

              </div>
            </div>

        </br>




        <div class="ingredient-container">

          <% @recipe.doses.each do |dose| %>

          <div class="test-in">

            <div class="card-ingredients">
              <div class="picture-ingredient" style="background-size: cover; background-repeat: no-repeat; background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= if dose.ingredient.picture.url == nil
                image_path('https://placeholdit.co//i/500x500?')
              else
                cl_image_path(dose.ingredient.picture.url)
              end
              %>')">
            </div>

            <div class="dose-container">

              <div class="ingredient-name">

                <p> <%= dose.ingredient.name.capitalize %></p>
              </div>
              <div class="dose-description">
                <span class='qty'>
                  <%= dose.quantity %>
                </span>
                <%= ' ' + dose.unit if dose.unit %>
              </div>
              <div class="initial-qty" style='display: none;'>
                <%= dose.quantity %>
              </div>
            </div>
          </div>
        </div>
        <%end%>
      </div>
    </div>

  </div>
</br>

<div class="row">

  <div class=" col-xs-12">
    <hr class="hr-danger hidden-xs" />

    <div class="number-person-eat">
      <form class="form-inline select-nbr">
        <label class="control-label"></label>
        <%="I want to make this recipe for  :" %><select class="form-control" id='count'>
        <option value='1'>1</option>
        <option value='2'>2</option>
        <option value='3'>3</option>
        <option value='4'>4</option>
        <option value='5'>5</option>
        <option value='6'>6</option>
        <option value='7'>7</option>
        <option value='8'>8</option>
      </select><%="    "%> <btn  class="btn btn-danger btn-user hidden-xs"><i class="fa fa-user hidden-xs" > </i></btn>
    </form>
  </div>
  <hr class="hr-danger hidden-xs" />

</br>

</div>
</div>
    <div class="col-xs-12 col-lg-12 ">
      <div class="infos container5" >
        <div class="cooking-time">
          <h4><i class="fa fa-clock-o" aria-hidden="true"></i><b> Cooking : <%= @recipe.cooking_time %></b></h4>
        </div>
        <div class="preparation-time">
          <h4><%= if @recipe.preparation_time == nil
          else
            "Preparation: #{@recipe.preparation_time}"
          end
          %></h4>
        </div>
      </div>


      <div class="recipe-description text-justify" >
        <p><%= @recipe.description %></p>
      </div>
      </div>







<%= render "recipes/reviews" %>

</div>
</div>
</div>
</div>
</div>
</div>

<%= content_for :after_js do %>
<script>

  $(document).ready(function() {
    $('.select-nbr').change(function() {
      var multiplier = parseInt($('#count').val());
      $('.qty').each(function() {
        var qty = parseInt($(this).parent().siblings('.initial-qty').text());
        $(this).html( qty * multiplier);
      });
    });
  });
</script>
<% end %>

app/views/recipes/index.html.erb
<!-- On a un container qui englobe toute la page sous la navbar.
  Dedans il y a une banner avec le titre "Recettes".
  En dessous les cartes en responsive, nommées total-card-recipes, et composées d'une photo nommée card-picture, et du titre avec le coeur des favoris en JS nommé card-name-link -->

<div class="container">
  <div class="banner">
    <% if @recipes.blank? %>
      <h2>Il n'y pas de recette disponible <%= params[:search] %>.</h2>
      <% else %>
      <h3><b> Recettes</b></h3>
    <% end %>
  </div>
  <% @recipes.each do |recipe| %>
    <div class="col-xs-6 col-sm-4 col-md-3">
      <div class="total-card-recipes col-xs-12">
        <%= link_to recipe_path(recipe) do %>
          <div class="card-picture" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= if recipe.picture.url == nil
              image_path('https://placeholdit.co//i/500x500?')
            else
              cl_image_path recipe.picture.url
            end
            %>')">
          </div>
        <% end %>
          <%= link_to recipe_path(recipe) do %>
            <div class='titre-recette'><%=recipe.name.capitalize %>
            <% if current_user %>
              <% if Favorite.where(recipe_id: recipe.id, user_id: current_user.id).count > 0 %>
                <%= link_to favorite_path(recipe), :method => :delete, remote: true, class: "favorite" do %>
                  &nbsp &nbsp<span class="fa fa-heart"></span>
                <% end %>
              <% else %>
                <%= link_to favorites_path(recipe_id: recipe.id), :method => :post, remote: true, class: "favorite" do %>
                   &nbsp &nbsp <span class="fa fa-heart-o"></span>
                <% end %>
              <% end %>
            <% end %>
            </div>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

<!-- Ci dessous le code en JS permemttant de faire changer le coeur des favoris -->
<%= content_for :after_js do %>
  <script>
  const btns = document.querySelectorAll('.favorite');
  btns.forEach((btn) => {
    btn.addEventListener('click', (event) => {
        const span = btn.querySelector('span');
        span.classList.toggle('fa-heart');
        span.classList.toggle('fa-heart-o');
    });
  });


/* Code a garder en attendant de savoir ce qu'on va faire. Algolia ou autre.

  // ALGOLIA
  var client = algoliasearch("NT0MM889NI", "3773b457ace95ffa42c5aeccd38270c6");
  var index_recipe = client.initIndex('Recipe_production');
  var index_ingredient = client.initIndex("Ingredient_production");

  const searchbar = document.getElementById("aa-search-input");
  const recipes = document.getElementById('recipes');

  const banner = document.getElementById("banner");
  const marketing_promise = document.getElementById("marketing-promise");
  var recipe_html = recipes.innerHTML;
  var banner_class = banner.classList;
  var banner_html = banner.innerHTML;
  var marketing_promise_html = marketing_promise.innerHTML;

  function capitalize(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  }
  function downcase(string) {
    return string.charAt(0).toLowerCase() + string.slice(1);
  }


  const search = (event) => {
    index_recipe.search(
      {
        query: searchbar.textContent,
        hitsPerPage: 10,
        ignorePlurals: true,
      },
      function searchDone(err, content) {
        recipes.innerHTML = "";
        marketing_promise.innerHTML = "<br><br>";
        banner.classList.remove("banner");
        banner.classList.add("banner-search");

        if (!searchbar.textContent == "") {
          content.hits.forEach((hit) => {

            recipes.insertAdjacentHTML("beforeend", `
              <div class="col-xs-12 col-sm-3 col-md-3">
                <div class="total-card-recipes">
                  <a href="/recipes/${hit.objectID}">
                    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('${hit.picture.picture.url}')">
                    </div>
                  </a>
                  <div class="card-name-link">
                    <a href="/recipes/${hit.objectID}">${hit.name}</a>
                  </div>
                </div>
              </div>
            `)
          })
        } else {
          recipes.insertAdjacentHTML("beforeend", `${recipe_html}`);
          banner.classList.remove('banner-search');
          banner.classList.add("banner");
          marketing_promise.innerHTML = marketing_promise_html;
        }
      }
    );
  }

  searchbar.addEventListener("keyup", search);

  var lastQuery = '';
  $('#aa-search-input').textcomplete([
    {
      // #3 - Regular expression used to trigger the autocomplete dropdown
      match: /(^|\s)[^\s](\w*(?:\s*\w*))$/,
      // #4 - Function called at every new keystroke
      search: function(query, callback) {
        lastQuery = query;
        index_ingredient.search(lastQuery, { hitsPerPage: 5 })
          .then(function searchSuccess(content) {
            if (content.query === lastQuery) {
              callback(content.hits);
            }
          })
          .catch(function searchFailure(err) {
            console.error(err);
          });
      },
      // #5 - Template used to display each result obtained by the Algolia API
      template: function (hit) {
        // Returns the highlighted version of the name attribute
        // if (!searchbar.value == "") {
          return '<img src="'+ hit.picture.picture.url +'" /></div>' + downcase(hit._highlightResult.name.value) + '';
        // }
      },
      // #6 - Template used to display the selected result in the textarea
      replace: function (hit) {
        var html = '<a class="tag-item" href="">';
        html += '<div class="picture-wrapper"><img src="'+ hit.picture.picture.url +'" /></div>';
        html += '<span class="label">' + capitalize(hit.name) + '</span></a>';
        html += " "
        return html;
      },

    }
  ], {
      // #7 - Special adapter to handle HTMLContentEditable divs
      adapter: $.fn.textcomplete.HTMLContentEditable,
  });

  // prevent default behaviour of the search form (i.e prevent from refreshing)
  const bindConfirm = (element) => {
    element.addEventListener("submit", (event) => {
        event.preventDefault();
    });
  };
  document.querySelectorAll(".confirmable").forEach(bindConfirm)

*/

  </script>
<% end %>

app/views/recipes/index.js.erb
 const newSearchForm = document.getElementById('search');
 const recipes = document.getElementById('recipes');
 recipes.innerHTML = "";
 recipes.insertAdjacentHTML("beforeend", "<%= j render 'recipes', recipe: @recipes %>");

app/views/recipes/show.html.erb
<div class="containerrr">
  <div class="row">
    <div class="col-xs-12 col-lg-3 stick">
      <div class="kardo hoverkard">


        <div class="infoe">

          <div class="cardoue" style="background-size: cover; background-repeat: no-repeat; background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= if @recipe.picture.url == nil
            image_path('https://placeholdit.co//i/500x500?', class: "picture-recipe")
          else
            cl_image_path @recipe.picture.url
          end
          %>')">
        </div>
        <div>
          <p class="share-recipe">
            <strong>SHARE THIS RECIPE </strong>
          </p>
          <%= social_share_button_tag(@recipe.name, 'data-twitter-title' => "Yum-yum, this recipe seems delicious !! #{@recipe.name}", 'data-facebook-title' => "Yum-yum, this recipe seems delicious !! #{@recipe.name}" )%>
        </div>
      </div>
    </div>




  </div>

  <div class="col-xs-12 col-lg-9">

    <div class="kardo favorite-section">

      <div class="row">

        <a class="pinned-item btn-special colorblue" href="#seereview"> See the reviews ! </a>


        <div class='row'>

          <div class="recipe-info-content">

            <div class="col-xs-12 col-lg-12">

              <div class="recipe-title ">
                <h2><%= @recipe.name.capitalize %></h2>
                          </br>
                           </br>

              </div>
            </div>

        </br>




        <div class="ingredient-container">

          <% @recipe.doses.each_with_index do |dose, index| %>

          <div class="test-in">


            <div class="card-ingredients">
              <div class="picture-ingredient" style="background-size: cover; background-repeat: no-repeat; background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= if dose.ingredient.picture.url == nil
                image_path('http://res.cloudinary.com/dgmpokhth/image/upload/v1507388190/nlrttkdtprmstqo5rvda.jpg')
              else
                cl_image_path(dose.ingredient.picture.url)
              end
              %>')">
            </div>

            <div class="dose-container">

              <div class="ingredient-name">

                <p> <%= dose.ingredient.name.capitalize %></p>
              </div>
              <div class="dose-description">
                <span id='qty <%=index%>'>
                  <%= dose.quantity %>
                </span>
                <%= ' ' + dose.unit if dose.unit %>
              </div>
              <div class="initial-qty" style='display: none;'>
                <%= dose.quantity %>
              </div>
            </div>
          </div>
        </div>
        <%end%>
      </div>
    </div>

  </div>
</br>

<div class="row">

  <div class=" col-xs-12">
    <hr class="hr-danger hidden-xs" />

    <div class="number-person-eat">
      <form class="form-inline select-nbr">
        <%="I want to make this recipe for  :" %><select class="form-control" id='count'>
        <option value='1'>1</option>
        <option value='2'>2</option>
        <option value='3'>3</option>
        <option value='4'>4</option>
        <option value='5'>5</option>
        <option value='6'>6</option>
        <option value='7'>7</option>
        <option value='8'>8</option>
      </select><%="    "%> <btn  class="btn btn-danger btn-user hidden-xs"><i class="fa fa-user hidden-xs" > </i></btn>
    </form>
  </div>
  <hr class="hr-danger hidden-xs" />

</br>

</div>
</div>
    <div class="col-xs-12 col-lg-12 ">
      <div class="infos container5" >
        <div class="cooking-time">
          <h4><i class="fa fa-clock-o" aria-hidden="true"></i><b> Cooking : <%= @recipe.cooking_time %></b></h4>
        </div>
        <div class="preparation-time">
          <h4><%= if @recipe.preparation_time == nil
          else
            "Preparation: #{@recipe.preparation_time}"
          end
          %></h4>
        </div>
      </div>


  <div class="recipe-description text-justify" >
    <p><%= @recipe.description %></p>
  </div>
</div>




<%= render "recipes/reviews" %>

</div>
</div>
</div>
</div>
</div>
</div>

<%= content_for :after_js do %>
<script>

  $(document).ready(function() {
    $('.select-nbr').change(function() {
      var multiplier = parseInt($('#count').val());
      <% @recipe.doses.each_with_index do |dose, index| %>
        <% if dose.ingredient.can_change %>
         var qty = <%= dose.quantity %>
         var result = document.getElementById('qty <%=index%>')
         result.innerHTML = qty * multiplier
       <% end %>
     <% end%>
    });
  });

</script>
<% end %>