config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root to: 'recipes#index'
  resource :profile, :only => :show, :as => :current_profile
  resource :profile, only: [ :edit, :destroy, :update ]


  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :recipes, only: [ :index, :show, :new, :create ] do
    resources :reviews, only: [ :new, :create]
    collection do
      get 'search'
    end
  end

  resources :doses, only: [ :new, :create, :destroy, :edit, :update ]

  resources :ingredients

  resources :reviews, only: [ :destroy ]


  resources :favorites, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_card.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to recipe_path(recipe) do %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= if recipe.picture.url == nil
          image_path('https://placeholdit.co//i/500x500?')
        else
          cl_image_path recipe.picture.url
        end
        %>')">
      </div>
      <%end%>

      <div class="card-name-link">
        <%= link_to recipe_path(recipe) do %>
        <%=recipe.name.capitalize%>
        <% if recipe.reviews.size != 0 %>
        <% arr = [] %>
        <% recipe.reviews.each do |review| %>
        <% arr << review.rating %>
        <% end %>
        <% average = arr.inject{ |sum, el| sum + el }.to_f / arr.size %>
        <p> rating : <%= average.round(1) if average %> / 5</p>
        <% else %>
        <p> waiting for a rating !</p>
        <%end%>
        <%end%>
      </div>
    </div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a><i class="fa fa-instagram"></i></a>
    <a href="https://www.facebook.com/FastAndDeliciouss/" target="_blank" ><i class="fa fa-facebook"></i></a>
    <a><i class="fa fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">

  <!-- Search Icon -->
  <form class="confirmable" >
    <div class="aa-input-container" id="aa-input-container">
      <div type="search" id="aa-search-input" class="aa-input-search autocomplete-textarea" name="search" autocomplete="off" contenteditable="true">
      </div>
      <svg class="aa-input-icon" viewBox="654 -372 1664 1664">
        <path d="M1806,332c0-123.3-43.8-228.8-131.5-316.5C1586.8-72.2,1481.3-116,1358-116s-228.8,43.8-316.5,131.5  C953.8,103.2,910,208.7,910,332s43.8,228.8,131.5,316.5C1129.2,736.2,1234.7,780,1358,780s228.8-43.8,316.5-131.5  C1762.2,560.8,1806,455.3,1806,332z M2318,1164c0,34.7-12.7,64.7-38,90s-55.3,38-90,38c-36,0-66-12.7-90-38l-343-342  c-119.3,82.7-252.3,124-399,124c-95.3,0-186.5-18.5-273.5-55.5s-162-87-225-150s-113-138-150-225S654,427.3,654,332  s18.5-186.5,55.5-273.5s87-162,150-225s138-113,225-150S1262.7-372,1358-372s186.5,18.5,273.5,55.5s162,87,225,150s113,138,150,225  S2062,236.7,2062,332c0,146.7-41.3,279.7-124,399l343,343C2305.7,1098.7,2318,1128.7,2318,1164z" />
      </svg>
    </div>
  </form>

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-logo" do %>
    <%= image_tag "logo_five_blanc.png", style: "background-image" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.profile.picture.url != nil
              avatar_url = current_user.profile.picture
             else
              avatar_url = "http://placehold.it/30x30"
             end %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to current_profile_path do %>
              <i class="fa fa-user"></i> Profile
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to new_user_session_path do %>
        <i class="fa fa-sign-in navbar-wagon-item" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
      <% if user_signed_in? %>

    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to current_profile_path do %>
          <i class="fa fa-user"></i> Profile
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>


      </ul>
       <% else %>
       <%= link_to new_user_session_path do %>
        <i class="fa fa-sign-in navbar-wagon-item " aria-hidden="true"></i>
      <% end %>
    <% end %>
    </div>
  </div>
</div>